"""password hash

Revision ID: cb9c19166c21
Revises: e3adc256db90
Create Date: 2018-03-30 19:55:38.011871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9c19166c21'
down_revision = 'e3adc256db90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_column('user', 'password_has')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_has', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
